my_recipes_dos_homepage:
    path:     /
    defaults: { _controller: MyRecipesDosBundle:Default:index }

# muestra el listado de recetas.
recipes_list:
    path:     /recipes/
    host:     elrincondelaura.com
    defaults: { _controller: MyRecipesDosBundle:Recipe:list }
    methods:  GET

# Creo una receta.
recipes_create:
    path:     /recipes/create/
    host:     elrincondelaura.com
    defaults: { _controller: MyRecipesDosBundle:Recipe:create }
    methods:  GET

# Modifico una receta.
recipes_update:
    path:     /recipes/update/{recipe_id}
    host:     elrincondelaura.com
    defaults: { _controller: MyRecipesDosBundle:Recipe:update }
    methods:  GET

# Elimino una receta.
recipes_delete:
    path:     /recipes/delete/{recipe_id}
    host:     elrincondelaura.com
    defaults: { _controller: MyRecipesDosBundle:Recipe:delete }
    methods:  GET

# muestra la receta concreta indicada por url.
recipes_show:
    path:     /recipes/{recipe_url}
    host:     elrincondelaura.com
    defaults: { _controller: MyRecipesDosBundle:Recipe:show }
    methods:  GET
    requirements:
        recipe_url: "[a-zA-Z-]{2,50}"
